# Generated by Django 5.1.7 on 2025-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('DR', 'Drama'), ('CO', 'Comedy'), ('HO', 'Horror'), ('RO', 'Romance'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('DO', 'Documentary'), ('TH', 'Thriller')], max_length=2)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(default='image.jpg', upload_to='movie-images/')),
            ],
        ),
    ]
