# Generated by Django 5.1.7 on 2025-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='movie-images/'),
        ),
    ]
