# Generated by Django 5.1.7 on 2025-03-19 05:17

import django.core.validators
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name=[music.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debut',
            field=models.PositiveIntegerField(verbose_name=[music.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, verbose_name=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
